version: 0.1

phases:
  install:
    commands:
      - echo Nothing to do in the install phase...
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./gradlew install
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/store-0.0.1-SNAPSHOT.jar
  discard-paths: yes