version: 0.1

environment_variables:
  plaintext:
    JAVA_HOME: "/usr/lib/jvm/java-8-openjdk-amd64"

phases:
  install:
    commands:
      - add-apt-repository -y ppa:cwchien/gradle
      - apt-get update -y
      - apt-get install -y gradle
  pre_build:
    commands:
      - echo Nothing to do here
  build:
    commands:
      - echo Build started on `date`
      - gradle build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/store-0.0.1-SNAPSHOT.jar
  discard-paths: yes